#!/usr/bin/env bash
# preflight.sh — Phase 0 read-only baseline. Safe to run any time (no motion/sound,
# no mutation). Regenerates PREFLIGHT.md. Mutating Phase-0 steps (SSH key install,
# password rotation, smoke tests) are supervised — see robot_admin.sh / `make smoke`.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
source "$HERE/lib.sh"
load_env

HOST="$(robot_host)"
BASE="http://$HOST:8000"
SSH_USER="${REACHY_SSH_USER:-pollen}"
OUT="$ROOT/PREFLIGHT.md"
EMO_DS="pollen-robotics/reachy-mini-emotions-library"

info "robot host: $HOST"
docs_code="$(curl -s -m 8 -o /dev/null -w '%{http_code}' "$BASE/docs" 2>/dev/null || echo 000)"
status_json="$(curl -s -m 8 "$BASE/api/daemon/status" 2>/dev/null || echo '{}')"
state_keys="$(curl -s -m 8 "$BASE/api/state/full" 2>/dev/null | jq -r 'if type=="object" then (keys|join(", ")) else "n/a" end' 2>/dev/null || echo 'n/a')"
volume="$(curl -s -m 8 "$BASE/api/volume/current" 2>/dev/null | jq -r '.volume // "?"' 2>/dev/null || echo '?')"
emo_count="$(curl -s -m 8 "$BASE/api/move/recorded-move-datasets/list/$EMO_DS" 2>/dev/null | jq 'if type=="array" then length else (.moves|length)? // 0 end' 2>/dev/null || echo 0)"

# Battery: the daemon exposes none if state/full has no battery/charge/voltage key.
if echo "$state_keys" | grep -qiE 'batter|charge|voltage'; then battery="reported in /api/state/full"; else battery="none (LED-only; daemon exposes no charge)"; fi

# SSH (key-based only; never blocks on a password prompt).
if ssh -o BatchMode=yes -o ConnectTimeout=5 "$SSH_USER@$HOST" true 2>/dev/null; then
  ssh_ok=yes
  os_ver="$(ssh -o BatchMode=yes "$SSH_USER@$HOST" 'cat /etc/os-release 2>/dev/null | sed -n "s/^PRETTY_NAME=//p" | tr -d \"' 2>/dev/null)"
  daemon_active="$(ssh -o BatchMode=yes "$SSH_USER@$HOST" 'systemctl is-active reachy-mini-daemon 2>/dev/null' 2>/dev/null)"
  sdk_ver="$(ssh -o BatchMode=yes "$SSH_USER@$HOST" '/venvs/apps_venv/bin/python -c "import reachy_mini,sys; print(reachy_mini.__version__)" 2>/dev/null' 2>/dev/null)"
else
  ssh_ok=no; os_ver="(ssh key not installed)"; daemon_active="(ssh key not installed)"; sdk_ver="(ssh key not installed)"
fi

[ "$docs_code" = "200" ] && ok "daemon /docs 200" || err "daemon /docs -> $docs_code"
[ "$ssh_ok" = yes ] && ok "ssh key works" || warn "ssh key NOT installed (see MORNING.md: make robot-keyinstall)"

daemon_state="$(echo "$status_json" | jq -r '.state // "?"' 2>/dev/null)"
wireless="$(echo "$status_json" | jq -r '.wireless_version // "?"' 2>/dev/null)"

cat > "$OUT" <<EOF
# PREFLIGHT.md (generated by \`make preflight\` — no personal data)

_Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ). Robot host generic; reserved IPs live in .env._

## Daemon (HTTP, read-only)
- \`/docs\`: HTTP $docs_code
- daemon state: \`$daemon_state\`, wireless: \`$wireless\`
- current volume: $volume
- \`/api/state/full\` keys: $state_keys
- **battery API: $battery**
- emotion moves in \`$EMO_DS\`: $emo_count

## SSH / on-robot (key-based; read-only)
- ssh key working: $ssh_ok
- ReachyMiniOS: $os_ver
- reachy-mini-daemon active: $daemon_active
- \`reachy_mini\` in /venvs/apps_venv: $sdk_ver

## Supervised Phase-0 steps (NOT done here — see MORNING.md)
- SSH key install + factory password rotation: \`make robot-keyinstall\`, \`make robot-rotate-pass\`
- Live smoke (antenna/emotion/sound/camera): \`make smoke\` (announces, asks first)
- Lower volume to HOUSE.md ceiling: \`make robot-set-volume\`
- Attic PC inventory + Phase 4: attic was offline; \`make attic-inventory BRAIN_HOST=<ip>\`
EOF

ok "wrote $OUT"
